#!/usr/bin/env bash
# Regenerate the pinned dependency locks for every shippable AI profile (issue #114).
#
# WHY LOCKS AT ALL: apps/ai/requirements*.txt carry open floors (`ultralytics>=8.4.115`), so an
# audit of those files reports on whatever the resolver picked THIS MORNING — not on what a
# deployment can actually install. The gate has to examine shippable versions, so it examines these.
#
# WHY A FIXED PLATFORM: torch pulls a different tree per OS and per Python. Compiled on a Mac the
# `nvidia-*` CUDA wheels vanish entirely, and the gate would silently stop covering the largest
# native dependency tree in the product. Pinned to what the shipped image and the box both run.
#
# Run this after ANY edit to apps/ai/requirements*.txt, and commit the result. CI does not run it —
# it verifies the committed locks still match their inputs (scripts/check_ai_locks.py) and audits
# them. A lock regenerated by CI would be a lock nobody reviewed.
set -euo pipefail

UV_VERSION="0.8.20"
PYTHON_VERSION="3.12"
PLATFORM="x86_64-unknown-linux-gnu"

cd "$(dirname "$0")/.."
OUT="apps/ai/constraints"
mkdir -p "$OUT"

uv_bin="$(command -v uv || true)"
if [ -z "$uv_bin" ]; then
  echo "uv not found. Install it with: pip install 'uv==${UV_VERSION}'" >&2
  exit 1
fi
echo "using $("$uv_bin" --version) (expected ${UV_VERSION})"

# The profile -> inputs mapping lives in scripts/check_ai_locks.py and is read from there, so it
# is written once. A profile added there is locked here automatically.
python3 scripts/check_ai_locks.py --profiles | while IFS=$'\t' read -r name inputs; do
  echo "==> ${name}: ${inputs}"
  # shellcheck disable=SC2086  # inputs is a deliberately word-split list of requirement files
  "$uv_bin" pip compile --quiet \
    --python-version "$PYTHON_VERSION" \
    --python-platform "$PLATFORM" \
    --no-header \
    -o "${OUT}/${name}.lock" ${inputs}
  python3 scripts/check_ai_locks.py --stamp "${name}"
done

echo
echo "verifying..."
python3 scripts/check_ai_locks.py

echo
echo "done. Review the diff, then commit ${OUT}/*.lock"
