#!/bin/sh
# Heldar one-liner installer (OPEN build: kernel + generic apps). Review before running:
#
#   curl -fsSL https://heldar.swmengappdev.workers.dev/install.sh | sh
#
# It detects Docker (never installs a daemon), writes ~/heldar/{compose.yml,mediamtx.yml,.env},
# and starts the stack. LAN defaults (auth off) — see docs/PRODUCTION.md to harden for the internet.
#
# Env overrides:
#   HELDAR_DIR=~/heldar             install directory
#   HELDAR_VERSION=latest           image tag to pin
#   HELDAR_INSTALL_DRY_RUN=1        write files but do not `docker compose up` (for testing)
set -eu

RAW_URL="${HELDAR_RAW_URL:-https://raw.githubusercontent.com/Straits-AI/heldar/HEAD/deploy}"
DIR="${HELDAR_DIR:-$HOME/heldar}"

say() { printf '\033[1;33m[heldar]\033[0m %s\n' "$1"; }
die() { printf '\033[1;31m[heldar] error:\033[0m %s\n' "$1" >&2; exit 1; }

# 1. Preconditions — detect only; we never install the Docker daemon for you.
command -v docker >/dev/null 2>&1 \
  || die "Docker is not installed. See https://docs.docker.com/engine/install/ then re-run."
if docker compose version >/dev/null 2>&1; then
  COMPOSE="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE="docker-compose"
else
  die "Docker Compose v2 is not available. Install the Compose plugin, then re-run."
fi
docker info >/dev/null 2>&1 \
  || die "The Docker daemon is not reachable (not running, or you lack permission). Start Docker (or add yourself to the 'docker' group) and re-run."
# The compose stack uses Linux host networking (network_mode: host). Docker Desktop on macOS runs
# containers in a VM, so host-net ports (the :8080 dashboard, MediaMTX) never reach the Mac itself.
if [ "$(uname -s)" = "Darwin" ]; then
  say "WARNING: macOS detected — the stack needs Linux host networking; on Docker Desktop the dashboard at :8080 will NOT be reachable. Run this on a Linux host instead."
fi

say "Installing into $DIR"
mkdir -p "$DIR"

# 2. Fetch the compose file + MediaMTX config from the public repo (HEAD = its default branch).
fetch() { curl -fsSL "$1" -o "$2" || die "download failed: $1"; }
fetch "$RAW_URL/compose.yml" "$DIR/compose.yml"
fetch "$RAW_URL/mediamtx.yml" "$DIR/mediamtx.yml"

# 3. Generate .env once (keep an existing one). A generated key encrypts camera creds at rest even on
#    the LAN profile; store it safely (losing it means re-entering camera passwords).
if [ ! -f "$DIR/.env" ]; then
  KEY=""
  command -v openssl >/dev/null 2>&1 && KEY="$(openssl rand -base64 32)"
  {
    echo "# Generated by install.sh — LAN defaults. See docs/PRODUCTION.md to harden."
    echo "HELDAR_VERSION=${HELDAR_VERSION:-latest}"
    [ -n "$KEY" ] && echo "HELDAR_SECRET_KEY=$KEY"
  } >"$DIR/.env"
  say "Wrote $DIR/.env"
else
  say "Keeping existing $DIR/.env"
fi

if [ "${HELDAR_INSTALL_DRY_RUN:-0}" = "1" ]; then
  say "DRY RUN — wrote files to $DIR, skipping startup."
  exit 0
fi

# 4. Pull + start.
say "Pulling images and starting (the first run downloads a few hundred MB)…"
(cd "$DIR" && $COMPOSE pull && $COMPOSE up -d)

say "Heldar is starting. Dashboard: http://localhost:8080"
say "Logs:  (cd $DIR && $COMPOSE logs -f core)"
say "Stop:  (cd $DIR && $COMPOSE down)"
say "Add the AI worker later:  (cd $DIR && $COMPOSE --profile ai up -d)"
