import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Heldar docs sidebar. Explicitly defined (not autogenerated) so the section
 * order is stable.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: ['getting-started/quickstart', 'getting-started/deploy'],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: ['concepts/architecture', 'concepts/open-core'],
    },
    {
      type: 'category',
      label: 'Develop',
      items: [
        'develop/build-a-module',
        'develop/sidecar-plugins',
        'develop/ai-worker',
        'develop/webhooks',
      ],
    },
    {
      type: 'category',
      label: 'Operate',
      items: ['operate/operate', 'operate/hosting-the-docs'],
    },
  ],
};

export default sidebars;
